---
abstract: "Get a hash of your current 'my' variables"
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: lexicals
name: lexicals
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  PadWalker: 1.92
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.19
